language: php
php:
  - '7.3'
before_script: 
  - composer install -o --no-progress
script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml
after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml
deploy:
  provider: heroku
  api_key:
    secure: 7bed4b4f-ae77-4495-acf1-58c45f8887f4
